SAM_base:
    model: SAM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    interaction_type: "SAM2E"
    aggregation: "concat"
    num_interaction_layers: 3
    use_residual: False
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'
