### Tiny data for demo only
tiny_seq:
    data_root: ../data/
    data_format: npz
    train_data: ../data/tiny_seq/train.npz
    valid_data: ../data/tiny_seq/valid.npz
    test_data: ../data/tiny_seq/test.npz
