Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

MaskNet_test:
    model: MaskNet
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_hidden_activations: relu
    model_type: SerialMaskNet
    parallel_num_blocks: 1
    parallel_block_dim: 64
    reduction_ratio: 1
    emb_layernorm: True
    net_layernorm: True
    net_dropout: 0
    epochs: 1
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'

MaskNet_default: # This is a config template
    model: MaskNet
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    dnn_hidden_units: [400, 400, 400]
    dnn_hidden_activations: relu
    model_type: SerialMaskNet
    parallel_num_blocks: 1
    parallel_block_dim: 64
    reduction_ratio: 1
    emb_layernorm: True
    net_layernorm: True
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'
