Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

ETA_test:
    model: ETA
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_dim: 64
    num_heads: 2
    use_scale: True
    attention_dropout: 0
    reuse_hash: True
    hash_bits: 32
    topk: 3
    short_target_field: []
    short_sequence_field: []
    long_target_field: adgroup_id
    long_sequence_field: click_sequence
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 20222023
    monitor: 'AUC'
    monitor_mode: 'max'

ETA_default: # This is a config template
    model: ETA
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_dim: 64
    num_heads: 2
    use_scale: True
    attention_dropout: 0
    reuse_hash: True
    hash_bits: 32
    topk: 5
    short_target_field: []
    short_sequence_field: []
    long_target_field: []
    long_sequence_field: []
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: 'AUC'
    monitor_mode: 'max'

