### Tiny data for tests only
taobao_tiny:
    data_root: ../data/
    data_format: csv
    train_data: ../data/tiny_data/train_sample.csv
    valid_data: ../data/tiny_data/valid_sample.csv
    test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                 active: True, dtype: str, type: categorical}]
    label_col: {name: clk, dtype: float}


taobao_tiny_h5:
    data_root: ../data/
    data_format: h5
    train_data: ../data/taobao_tiny_h5/train.h5
    valid_data: ../data/taobao_tiny_h5/valid.h5
    test_data: ../data/taobao_tiny_h5/test.h5


taobao_tiny_sequence:
    data_root: ../data/
    data_format: csv
    train_data: ../data/tiny_data/train_sample.csv
    valid_data: ../data/tiny_data/valid_sample.csv
    test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                 active: True, dtype: str, type: categorical},
         {name: "click_sequence", active: True, dtype: str, type: sequence, splitter: "^", max_len: 5,
          encoder: "MaskedAveragePooling", share_embedding: "adgroup_id"}]
    label_col: {name: clk, dtype: float}


taobao_tiny_pretrain:
    data_root: ../data/
    data_format: csv
    train_data: ../data/tiny_data/train_sample.csv
    valid_data: ../data/tiny_data/valid_sample.csv
    test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: "userid", active: True, dtype: str, type: categorical, embedding_dim: 8,
          pretrained_emb: "../data/tiny_data/userid_emb_dim8.h5", freeze_emb: False},
         {name: ["adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                 active: True, dtype: str, type: categorical}]
    label_col: {name: clk, dtype: float}